name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: autodesk-fusion-installer-${{ github.ref_name }}.zip
    steps:
      - run: |
          curl "https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Client%20Downloader.exe" -L --output installer.exe
      
      - shell: cmd
        run: |
          set __COMPAT_LAYER=RUNASINVOKER &&^
          start .\installer.exe &&^
          C:\Windows\System32\cmd.exe /c start /wait /min timeout.exe /t 1800 &&^
          (   C:\Windows\System32\taskkill.exe /f /im installer.exe || ^
          C:\Windows\System32\taskkill.exe /f /im streamer.exe || ^
          C:\Windows\System32\taskkill.exe /f /im Fusion360.exe || ^
          C:\Windows\System32\taskkill.exe /f /im FusionLauncher.exe   ) &&^
          dir

      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production" &&^
          7z.exe -v100m a "${{ github.workspace }}\${{ env.targetZip }}" &&^
          dir
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
