name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: autodesk-fusion-portable-${{ github.ref_name }}.zip
    steps:
      - run: |
          curl "https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Client%20Downloader.exe" -L --output installer.exe

      - uses: actions/checkout@v4
      
      - shell: cmd
        run: |
          start "" .\installer.exe &&^
          C:\Windows\System32\cmd.exe /c start /wait /min C:\Windows\System32\timeout.exe /t 1800 &&^
          C:\Windows\System32\taskkill.exe /f /im installer.exe &&^
          C:\Windows\System32\taskkill.exe /f /im streamer.exe &&^
          C:\Windows\System32\taskkill.exe /f /im Fusion360.exe &&^
          C:\Windows\System32\taskkill.exe /f /im FusionLauncher.exe

      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im installer.exe
          
      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im streamer.exe
             
      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im Fusion360.exe
    
      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im FusionLauncher.exe
        
      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\" &&^
          move /Y "6a0c9611291d45bb9226980209917c3d\FusionLauncher.exe.ini" ad7281617f9bd8f5795b94fde099c32079296a4e
      
      - shell: cmd
        run: move /H /Y /C "FusionLauncher.exe.Portable.cmd" "%LOCALAPPDATA%\Autodesk\webdeploy\production\ad7281617f9bd8f5795b94fde099c32079296a4e"
        
      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\ad7281617f9bd8f5795b94fde099c32079296a4e" &&^
          dir
        
      - shell: cmd
        run: |
          7z.exe -v100m a -tzip "${{ env.targetZip }}" "%LOCALAPPDATA%\Autodesk\webdeploy\production\ad7281617f9bd8f5795b94fde099c32079296a4e\" &&^
          dir
          
      - shell: cmd
        run: dir
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
