name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: autodesk-fusion-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4

      - shell: cmd
        continue-on-error: true
        run: |
          curl https://github.com/dirkarnez/exec-timeout/releases/download/v1.0.0/exec-timeout-v1.0.0-windows-latest.zip -L -O &&^
          7z x exec-timeout-v1.0.0-windows-latest.zip &&^
          dir &&^
          exec-timeout.exe 1800 "%CD%\Fusion Client Downloader.exe"

      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im streamer.exe
        
      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im "Fusion Client Downloader.exe"
        
      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im FusionLauncher.exe

      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im QtWebEngineProcess.exe

      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im AdskIdentityManager.exe

      - shell: cmd
        continue-on-error: true
        run: C:\Windows\System32\taskkill.exe /f /im ADPClientService.exe

        # Fusion360.exe running means installation complete, must be running
      - shell: cmd
        continue-on-error: false
        run: C:\Windows\System32\taskkill.exe /f /im Fusion360.exe

      - shell: cmd
        run: |
          tasklist
          
      - shell: cmd
        run: |
          dir
          
      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk" &&^
          dir

# Fusion360.ico
# Fusion360Develop.ico
# Fusion360Insider.ico
# Fusion360Major.ico
# Fusion360Minor.ico
# Fusion360PR.ico
# FusionLauncher.exe
# FusionLauncher.exe.ini

      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\6a0c9611291d45bb9226980209917c3d" &&^
          curl https://github.com/dirkarnez/regex-file-replace/releases/download/v1.0.0/regex-file-replace-v1.0.0-windows-latest.zip -L -O &&^
          7z x regex-file-replace-v1.0.0-windows-latest.zip &&^
          .\regex-file-replace.exe --regex="^cmd = .*" --replacement="cmd = \"\"Fusion360.exe\"\"" --filepath=FusionLauncher.exe.ini &&^
          type .\FusionLauncher.exe.ini
          
      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\" &&^
          move /Y "6a0c9611291d45bb9226980209917c3d\FusionLauncher.exe.ini" 1a197c6e79bef01edef1dc4f317d9f597820e633 &&^
          move /Y "6a0c9611291d45bb9226980209917c3d\FusionLauncher.exe" 1a197c6e79bef01edef1dc4f317d9f597820e633 &&^
          dir

      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\" &&^
          rmdir /s /q 6a0c9611291d45bb9226980209917c3d

      #   # %LOCALAPPDATA%\Autodesk\Common\Material Library\20240514-fy25-4.1.2
      # - shell: cmd
      #   run: |
      #     cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\1a197c6e79bef01edef1dc4f317d9f597820e633" &&^
      #     mkdir "USERPROFILE\AppData\Local\Autodesk\Common\Material Library\" &&^
      #     cd "USERPROFILE\AppData\Local\Autodesk\Common\Material Library" &&^
      #     move "%LOCALAPPDATA%\Autodesk\Common\Material Library\20240514-fy25-4.1.2" . &&^
      #     dir
          
      - shell: cmd
        run: move /Y "FusionLauncher.exe.Portable.cmd" "%USERPROFILE%\..\"
        
      - shell: cmd
        run: |
          cd /d "%LOCALAPPDATA%\Autodesk\webdeploy\production\1a197c6e79bef01edef1dc4f317d9f597820e633" &&^
          dir
        
      - shell: cmd
        run: |
          set CURRENT_DIRECTORY=%CD%
          echo %CURRENT_DIRECTORY% &&^
          cd /d "%USERPROFILE%\" &&^
          cd .. &&^
          md USERPROFILE\AppData\Local &&^
          cd "USERPROFILE\AppData\Local" &&^
          move "%LOCALAPPDATA%\Autodesk" . &&^
          7z.exe -v100m a -tzip "%CURRENT_DIRECTORY%\${{ env.targetZip }}" "USERPROFILE" "FusionLauncher.exe.Portable.cmd" &&^
          dir
          
      - shell: cmd
        run: dir
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
